name: Build

on: [pull_request, push]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: make setup_ubuntu

    - name: Generate PDF
      run: make -j$(nproc) ebook

    - uses: actions/upload-artifact@v3
      with:
        name: e-book PDF (Ubuntu)
        path: controls-engineering-in-frc-ebook.pdf

  archlinux:
    runs-on: ubuntu-latest
    container: archlinux/archlinux:base-devel
    timeout-minutes: 30
    steps:
    - name: Install Git
      run: sudo pacman -Sy --needed --noconfirm git

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Add Git repo as a safe directory
      run: git config --global --add safe.directory `pwd`

    - name: Install system dependencies
      run: |
        sudo pacman -Syu --noconfirm
        make setup_archlinux

    - name: Generate PDF
      run: |
        # Add perl modules (biber) to PATH
        source /etc/profile
        make -j$(nproc) ebook

    - uses: actions/upload-artifact@v3
      with:
        name: e-book PDF (Arch Linux)
        path: controls-engineering-in-frc-ebook.pdf

  windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: make setup_windows

    - name: Generate PDF
      run: |
        setx path "%PATH%;C:\texlive\2022\bin\win32"
        make -j1 ebook

    - uses: actions/upload-artifact@v3
      with:
        name: e-book PDF (Windows)
        path: controls-engineering-in-frc-ebook.pdf

  macos:
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install system dependencies
      run: make setup_macos

    - name: Generate PDF
      run: |
        eval `/usr/libexec/path_helper`
        make -j$(nproc) ebook

    - uses: actions/upload-artifact@v3
      with:
        name: e-book PDF (macOS)
        path: controls-engineering-in-frc-ebook.pdf
